steps:
- name: gcr.io/cloud-builders/docker
  args:
  - image
  - build
  - -t
  - asia.gcr.io/$PROJECT_ID/elquest-api
  - .

- name: gcr.io/cloud-builders/docker
  args:
  - image
  - push
  - asia.gcr.io/$PROJECT_ID/elquest-api

- name: gcr.io/cloud-builders/gcloud
  args:
  - run
  - deploy
  - elquest-api
  - --image=asia.gcr.io/$PROJECT_ID/elquest-api
  - --platform=managed
  - --region=asia-northeast1
  - --allow-unauthenticated
  - --memory=2048Mi
  - --concurrency=80
  - --port=8080
  - --set-cloudsql-instances=el-quest:asia-northeast1:elquest-db

timeout: 1600s
options:
  machineType: N1_HIGHCPU_8
