default: &default
  adapter: postgresql
  encoding: utf8
  port: 5432

development:
  <<: *default
  username: postgres
  database: souls_api_dev
  password: postgres
  host: localhost
  port: 5433

production:
  <<: *default
  database: souls_api_production
  username: <%= ENV.fetch("DB_USER") { "" } %>
  password: <%= ENV.fetch("DB_PW") { "" } %>
  host: <%= ENV.fetch("DB_HOST") { "" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


## Use local docker postgresql13
## `souls i run_psql` will create psql container

test:
  <<: *default
  username: postgres
  password: postgres
  database: souls_api_test
  host: localhost
  port: 5433

